radius: 10
repeated: 20 # в тиках (лучше 20)
hide_your_name: true # Скрыть видимость своего имени?

# Отображение ника. Можно, например, использовать префиксы LuckPerms и так далее.
display: "%player_name%"

# Добавление высоты (или X, Z) голограмме
vector:
  x: "0.0"
  y: "0.4"
  z: "0.0"

# Вектор голограммы над игроком
vector-2:
  x: "1.0"
  y: "1.0"
  z: "1.0"